### ISSUE TITLE
DRK: Delirium Bloodspiller/Quietus Feature

### ISSUE THREAD

**Issue by Xiniox** [Grammernatzi/XIVComboPluginExpandedest#28]
There's a feature for Warrior that changes the Storm's Path/Eye Combo and Mythril Tempest combo into Fell Cleave/Decimate when you're in Inner Release. 

Dark Knight should have a similar feature with Delirium, changing Souleater and Stalwart Soul into Bloodspiller/Quietus while under the effect of Delirium.

**Comment by Grammernatzi** [comment]
I removed this because you can actually use them while you're in Delirium now without using Delirium stacks. For example, if you need to build up MP for TBN, or gauge for living shadow. I could add it back if people *really* want it, but there's a big difference between how it used to be and how it is now.

**Comment by Grammernatzi** [comment]
Re-added with latest version

**Comment by Grammernatzi** [comment]
https://cdn.discordapp.com/attachments/277962421862268930/920435249916280832/DRK_EW_standard.png

Sorry, but I think I will be removing it after all. I don't want to add any features that make it literally impossible to play properly.
