### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by xkhsvcct** [Grammernatzi/XIVComboPluginExpandedest#31]
Can't get this to install in xlplugins.  I go to settings and custom repository, but none of the links I enter work.  Daemitus gave a link on his site that works, just to give you an example.  Also I think xlplugins is looking for a .dll file, which I can't find anywhere in your zip file or on your site.  Hope this gives you all the info you need.

**Comment by Rileytaugor** [comment]
You need to add this link there:
https://github.com/grammernatzi/MyDalamudPlugins/raw/master/pluginmaster.json

so 11. 12. 2021 v 18:13 odesílatel xkhsvcct ***@***.***>
napsal:

**Comment by xkhsvcct** [comment]
Thank you very much

**Comment by Rileytaugor** [comment]
Anytime, after that just go to the plugins page, search for it and type
/pcombo. Have fun ^

so 11. 12. 2021 v 18:28 odesílatel xkhsvcct ***@***.***>
napsal:

**Comment by Grammernatzi** [comment]
I purposefully obfuscated it by removing the link from the readme so that it would require a small amount more effort to install, as Daemitus does the same thing by only putting a link on his website and MyDalamudPlugins repository, not on the github page for the plugin. People can see the URL on the MyDalamadPlugins project I have, as well. I think the link being in a closed issue is fine, though, as it's far enough away from the front page of the repository. This was mostly done because it was starting to overtake his fork in popularity due to ease of access, and I felt bad about that since he does the majority of the work here.

**Comment by Rileytaugor** [comment]
I was having the same problems with it as well but i found it because
daemitus / XIVComboPlugin has it on the main page so i just followed the
same but on your profile. I dont see anything bad about putting your link
on your main site.

so 11. 12. 2021 v 19:14 odesílatel Adam ***@***.***> napsal:

**Comment by Grammernatzi** [comment]
Okay, I see, he put the repo on the readme now. I'll go ahead and do so as well, near the bottom.

**Comment by Rileytaugor** [comment]
Yeah, Not sure if he added it recently but i found it at the bottom of the
main page. Like i said, i dont see anything wrong with you putting your
link on the main page as well. Your plugin helps tons of people, so why
not.

so 11. 12. 2021 v 20:04 odesílatel Adam ***@***.***> napsal:
