### ISSUE TITLE
PLD Requiescat

### ISSUE THREAD

**Issue by FFXIVWytes** [Grammernatzi/XIVComboPluginExpandedest#4]
Hi,

I was just wondering about the decision to have the combo use confiteor when below 4000 MP. In most cases you will use Requiescat at 10000 MP and casting confiteor at 4000 MP is a loss of potency as you lose a holy spirit/circle cast.

Would it be possible to change the logic to use it at <3000 MP?

Thanks for your time and expanding the original addon. It's literally been a game changer!

**Comment by Grammernatzi** [comment]
You don't cast Confiteor at 4000 MP, you cast it below 4000 MP, so it's actually more like <= 3800 MP. If you're at 3600 MP or less (and don't have spirits within), you don't want to use another Holy Spirit, you will lose your Confiteor if you do. If you're at 3800 MP, you can wait a little for an MP tick to get Confiteor off along with 4 Holy Spirits. I tested it with multiple values and 3800 MP or less (which is basically what it amounts to) was by far the most comfy. If you use Requiescat when you have 9200 MP or more (8600 if you have spirits within), you will always get the 4 Holy Spirits/Circles + Confiteor, don't worry. The main issue with setting it to be 2800 or less (<3000, since MP is in multiples of 200 on PLD) is that it'd make using it below 9200 MP harder, because in that case you want to 3 Holy Spirit/Circle + Confiteor instead as you don't have enough MP for 4, and you'll be in-between 3000-4000 MP when you need to Confiteor. Regardless, I don't raid as Paladin, I'm just basing this off my testing and what I've read on the Balance. I'm willing to change it if it does present an issue, but so far, it's been okay.

**Comment by FFXIVWytes** [comment]
I definitely must have been counting wrong when I first enabled the addon. I tested it again and you are correct. Your mana does tick up during the duration of rescuecat resulting in the 4 holy spirits and then confiteor! Thanks for clarifying.

**Comment by Grammernatzi** [comment]
No prob! Again, if there are issues that crop up, be sure to let me know, I have been trying to be on top of fixing them.
