### ISSUE TITLE
Suggestions: Healers and Tanks

### ISSUE THREAD

**Issue by niserox** [Grammernatzi/XIVComboPluginExpandedest#48]
Hey there, I have a few suggestions that I think would be great additions. I'm unaware to the limitations of plugin programming, so I apologize if any of these are unfeasible/cannot be logically done.

**Use DoT first if target is undotted by you, then use spammables for healers:**
(SCH) Bio > Broil (Could also do Bio > Ruin II).
(WHM) Aero/Dia > Stone/Glare.
(AST) Combust > Malefic.

**Low level scaling:**
(SCH) Replace Adloquium > Physick (in low level content).
(AST) Replace Helios II > Helios I (in low level content).
(WHM) Replace Medica II > Medica I (in low level content).

**For all healers:** 
Use Rescue if targetting an ally, use Repose (Sleep) if targetting an enemy. Default should be Rescue for CD.
Replace Surecast > Lucid Dreaming if under 50% MP. (Or other numbers, 25% MP, etc.).

(AST) Draw > Redraw while Clarifying Draw is up (able to use Redraw), then changes back to Draw.
(AST) Celestial Opposition > Helios (I) when celestial oppositon is on CD.

(SCH) Change fairie ability buttons to summon a _**random**_ fairy (either Eos or Selene) if unsummoned. (This probably isn't possible due to limitations, but it could be neat to be able to mix things up a bit so you aren't stuck with the same fairy all the time).
(SCH) Chain Stratagem > Ruin II if chain stratagem is off CD.

(PLD) Replace Requiescat > Holy Circle while requiescat is up. (There's literally 0 reason to ever use Holy Circle outside of requiescat, so this just frees up a slot).
(PLD) Sheltron > Cover (or Intervention) if targetting an ally.

Thanks again for the great plugin. Really made me enjoy classes like GNB and SAM again.

**Comment by Grammernatzi** [comment]
> Use DoT first if target is undotted by you, then use spammables for healers:
(SCH) Bio > Broil (Could also do Bio > Ruin II).
(WHM) Aero/Dia > Stone/Glare.
(AST) Combust > Malefic.

Main reason I wouldn't like this is because you want to use DoTs before they fully run out for movement purposes. And often you don't want to DoT, either, like if the enemy is at low HP. It just seems like it'd be not helpful more often than not.

>Low level scaling:
(SCH) Replace Adloquium > Physick (in low level content).
(AST) Replace Helios II > Helios I (in low level content).
(WHM) Replace Medica II > Medica I (in low level content).

While I don't think these abilities are true replacements for each other, syncing them down probably would be harmless. So, maybe.

>For all healers:
Use Rescue if targetting an ally, use Repose (Sleep) if targetting an enemy. Default should be Rescue for CD.
Replace Surecast > Lucid Dreaming if under 50% MP. (Or other numbers, 25% MP, etc.).

Rescue I use as an MO, and I think that's the case for a lot of people, so I don't know how helpful this would be. The main cases you'd use Repose are usually in solo content, where Rescue would be useless, so it replacing it while it's on CD would be harmful.

Also, you should be using Lucid Dreaming on cooldown, not at an MP threshold. And even at low MP you'd often want to use Surecast first for mechanics, since you are only given an opportunity to single-weave most of the time and not being knocked back is the higher priority.

> (AST) Draw > Redraw while Clarifying Draw is up (able to use Redraw), then changes back to Draw.
(AST) Celestial Opposition > Helios (I) when celestial oppositon is on CD.

These I can see. I use play to draw, so I have no use for the former, but I can understand if people would want to use it. The second one makes sense, since you'd not really want to 'save' Celestial Opposition when it's on cooldown, and it will heal more than Helios will in 6s after use, and then more after that. However, needing instant HP might make it a hard call, like if you're dealing with raidwide damage spam. So it's a bit of an iffy thing. Healers are hard to make stuff for for this reason. 

> (SCH) Change fairie ability buttons to summon a random fairy (either Eos or Selene) if unsummoned. (This probably isn't possible due to limitations, but it could be neat to be able to mix things up a bit so you aren't stuck with the same fairy all the time).
(SCH) Chain Stratagem > Ruin II if chain stratagem is off CD.

The amount of work to make the summon random is probably just too much for the 'reward' at the moment, I apologize. The Ruin 2 one would make sense, as it doesn't really conflict with use of Ruin 2. The SCH 'opener' is kind of stupid, as you can see, but it doesn't conflict with it: 
![image](https://user-images.githubusercontent.com/869037/147085731-afbe9431-2607-49e8-bc49-73791f108b28.png)

> (PLD) Replace Requiescat > Holy Circle while requiescat is up. (There's literally 0 reason to ever use Holy Circle outside of requiescat, so this just frees up a slot).
(PLD) Sheltron > Cover (or Intervention) if targetting an ally.

Okay, I play a lot of PLD and the first one is just wrong. Holy Circle does barely less potency per second than your aoe combo (when you're out of fight or flight), and since it heals you, it's a way more efficient heal to use in pulls than Clemency. Holy Spirit might be a better candidate but, the thing is, you use it for your pre-pull opener, and you use it for emergency healing before you use Clemency. Confiteor is a good case, but we already have that as a feature.

Sheltron to Cover/Intervention, maybe. But I often use Cover/Intervention on Mouseover, or targeting <2> in party, as well, with ReAction, and I highly recommend everyone do that, honestly. 

I hope this wasn't too harsh, I apologize. I just have no-lifed this game and my personal rule is that I don't want any features to interfere with good gameplay options you'd use a decent chunk of the time. I'm not like Attick who takes the stance of 'if you wouldn't want it 0.00001% of the time for a very, very tiny benefit that could easily be missed: No', but I do still prefer to not add stuff if it'd get too in the way. There are some good ones in there, though, and I may add them later, like Chain > Ruin 2 (god knows SCH could use some hotbar reduction) and Draw to Redraw (even if I wouldn't use it). Again, I do hope I'm not being too harsh, here.

**Comment by niserox** [comment]
Not harsh at all! As I said, your plugin allowed me to re-enjoy classes like GNB and SAM again lol. I completely gapped on the Holy Circle healing potential, that's what I get for writing things at 1am ha. 

Thanks again for reading, and I hope I was able to give you some future ideas! :)

**Comment by Grammernatzi** [comment]
Yeah, for now I'll close it, but I'll definitely take a look at some things in the future. Probably the SCH thing is the most likely to be added because that job is just absolutely overloaded with buttons.
