### ISSUE TITLE
Warrior Suggestion

### ISSUE THREAD

**Issue by Syzzle07** [Grammernatzi/XIVComboPluginExpandedest#55]
Is it possible to make an option where when you use Infuriate it changes your Single Target skills to Inner Chaos? The same way it does when you use Inner Release and it changes the single target skills to Fell Cleave.

**Comment by Grammernatzi** [comment]
This isn't a good idea because you want to save Nascent Chaos a lot of the time; say, if you need to use Infuriate to keep its cooldown rolling, but want to use Inner Chaos during a raid buff coming up in 10 seconds. Using a GCD doesn't use up Nascent Chaos like it would Inner Release's stacks, so you can save it without worry and continue to do your combos. So I feel this would just invite bad play, unfortunately.

**Comment by Syzzle07** [comment]
I see. Yeah that makes alot of sense.
Thanks.
