### ISSUE TITLE
Black Mage suggestion

### ISSUE THREAD

**Issue by victorkikudome** [Grammernatzi/XIVComboPluginExpandedest#56]
Change Xenoglossy and Foul into Amplifier when available and you're not maxed on Polyglot.

Would be really nice if it also worked with the Scathe/Xenoglossy feature.

**Comment by Grammernatzi** [comment]
Fair enough, but wouldn't you also use Xenoglossy to weave in Amplifier to begin with after your opener? That might cause some issues doing so, since you generally want to use it as your first priority for weaving. Maybe if I did something similar to what I did for Nastrond/Stardiver and had it so if the GCD is less than 0.5s remaining, it doesn't replace it.

**Comment by Grammernatzi** [comment]
I added it, it should be okay the way I set it up.

**Comment by victorkikudome** [comment]
Huh, I did not think about that but your solution seems perfect.

What do you think about changing Thunder 3/4 into Sharpcast when available (and you don't have the sharpcast buff up)? 

Thanks!

**Comment by Grammernatzi** [comment]
Maybe with the same solution, perhaps. I'll look into it.

**Comment by Grammernatzi** [comment]
Added that as well; hopefully it works. Strangely, it seems Sharpcast is always on an invisible charge system, even before the Enhanced upgrade, you just can't use the second charge at all. It made cooldown tracking on it kind of odd, but I got it working.
