### ISSUE TITLE
Paladin combos

### ISSUE THREAD

**Issue by somerandomname1234** [Grammernatzi/XIVComboPluginExpandedest#74]
Hello dev sir,

I have three suggestions for paladin combo's.
1. replace Expiacion/circle of Scorn for the other one when its on cd.
2. replace Expiacion/circle of Scorn for Intervene when both are on cd.
3. replace Holy Spirit/Holy Circle for Confiteor (and possibly the rest of the Confiteor combo afterwards) when you have 1 stack of Requiescat.

Beste regards,
somerandomname1234

**Comment by Grammernatzi** [comment]
The Confiteor thing is already in as a 'secret'. So is the first one in the original plugin, so I can add that for parity's sake. I dunno how helpful the second one would be, though. While you use both intervenes in your opener, ideally you want to save one for movement and be able to use it at any time for the rest of the fight, since the DPS gain from using both charges in Fight or Flight is very small.

**Comment by somerandomname1234** [comment]
Oh I see, I only looked at the Expandedestest combo plugin. The features are already there, great thanks!
