### ISSUE TITLE
Issue with [Redoublement Combo Lockout Feature] queueing up Verthunder if pushed during the queue-up window.

### ISSUE THREAD

**Issue by DJFarr** [Grammernatzi/XIVComboPluginExpandedest#76]
Hi, love the additions to the plugin.

I was testing the RDM features and noticed that if i hit the supposed "unusable" Verflare that gets put there for the lockout, it would work fine (do nothing) if pushed normally, but if spammed and pressed during the queue up window, it would queue up verthunder to be cast.

I did record this just to show it off:
![Recorded4](https://user-images.githubusercontent.com/16067714/149083336-21f6d6f5-e66c-4f1f-b587-a77ce08ac8f9.gif)

**Possible Solution**: 
Swap verflare out for Physick just like the Moulinet lockout feature?

**Comment by Grammernatzi** [comment]
Yep, I know it does this. I do kind of prefer how it looks this way, and was honestly possibly going to do the same to Moulinet (I made it Physick as a joke). Hitting it and accidentally starting a verthunder cast is a lot less punishing than wasting your mana, at least. But, if you'd prefer this sort of thing to not happen, I could look into changing it.

**Comment by DJFarr** [comment]
Haha, in the back of my head I knew the Physick didn't make sense.
If this was a known thing and semi-intentional, I guess its not too bad then. I brought it up in case it'd been missed by accident.

I agree that casting something is less punishing than wasting black/white mana, but comparing it to the joke Moulinet-> Physick, I'd argue that starting a 5s(max) second cast is more punishing than doing nothing then going "oops" and starting a 2.5s cast, since hardcasting casting a verthunder or aero is still a complete waste of a full GCD.

With Moulinet turning into physick, hitting it does indeed do nothing, allowing the player to have that oops moment instead of  wasting either a full GCD or some mana resources.

Just some thoughts, up to you after all on whether you change it, I just think having it do nothing would work a bit better as a lockout feature.

Really enjoying the rest of the changes btw, solid work!

**Comment by Random-Stack-Random-Day** [comment]
@Grammernatzi Since you actually know why this happens, could you tell me how/why? It isn't just your library, I've noticed this is a couple combo libraries, but I haven't been able to personally figure out "why" it happens. (Reg the spamming during the queue window breaking the rules of the function)

**Comment by Grammernatzi** [comment]
It has to do with how the actual icon replacement works in the game. When you queue an action, it defaults to what that action currently is in the action manager. So, for Verflare, that defaults to Verthunder. And if you change the icon of that action, it queues up what the new action is too. This was a problem with the Monk AoE combo; Rockbreaker was turning into Shadow of the Destroyer during Perfect Balance, so when the Four-Point Fury combo was trying to use it, it would queue up Shadow of the Destroyer instead, messing up your combo. The solution was to move the standard combo onto Masterful Blitz, instead. 

As for changing it, I might, but I do rather like how it looks. And, honestly, the amount of times you should be pressing it would be rather low. If you press it during dualcast, the only downside is that you may get too much black mana (white mana if you have the verholy option enabled) or overwrite a proc (both of which are much less punishing now), and if you press it outside of dualcast, you can just cancel the cast. So I don't know if it's really too big of a problem. The button being greyed out alone helps deter unwanted presses, outside of if you've put it in a spot you habitually press because of muscle memory.

**Comment by DJFarr** [comment]
It definitely seems more complicated than I was expecting, but I'm still not sure why the same thing wouldn't be happening for Moulinet's Physick replacement? that one seemed to work fine as a lockout. is it because Physick has no lower level moves that turn into it?
If I'm thinking about it right, then as a 'fix' for the queue thing it could just be any other unusable ability.

I know you say you don't mind it and that it should be getting pressed much anyway, but maybe an extra option to make it work as a full lockout alongside the AoE combo's lockout wouldn't go astray.

**Comment by Grammernatzi** [comment]
The reason it doesn't happen with Moulinet is because nothing's replacing Physick, and Physick itself doesn't turn into any other action. If you try to force Verflare onto your bar (using, say, Reaction), it turns into Verthunder. Same thing if you type /ac Verflare (I believe, anyway, not in-game to test it). So, if you try to queue Physick, nothing happens, because you can't use Physick on Red Mage, and it's not turning into any other action.

I mean, if you'd really prefer a separate option to make sure you can't accidentally queue Verthunder, I could add it. I just try not to clog up the list *too* much. The Reaper list, for example, is already a giant list of spaghetti that I can't undo because if I did, it'd mess up people's hotbars.

**Comment by DJFarr** [comment]
The way it is right now, there are two combos labelled as lockout features, and they both work differently, with one allowing you to 'accidentally' queue up an unwanted move.

I think it would be best to have both act like the Physick replacement, even if it was a bit of a joke, because it actually works better as a real lockout feature.

If users did want to have it be a lockout that queued useful things up when hit, that is of course another option to consider.
i.e. it could be the melee combo when above 50, or jolt/something when below, etc.
Personally I'd pick the proper lockout over that though.

As for the long list of options, I have to say that coming from regular XIVCombo, I actually _loved_ seeing the long lists, there were so many things to pick and choose from and customise exactly how i wanted.

**Comment by Grammernatzi** [comment]
I can probably add an option later, then. Maybe the real flare would work instead. At the moment, though, I'm about to sleep, so I'll look at it when I wake up.

**Comment by Random-Stack-Random-Day** [comment]
@Grammernatzi Thanks for the detailed response on why it happens - That makes sense, and was what I was thinking. Been a question of mine since I found it in Nik's One-Button Summoner rotation.

**Comment by Grammernatzi** [comment]
Added option.

**Comment by DJFarr** [comment]
Tested and working, Thanks!
